[package]
name = "scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.53"
csv = "1.1.6"
flate2 = "1.0.23"
futures = "0.3.21"
octocrab = "0.16.0"
serde = "1.0.137"
tokio = { version = "1.18.0", features = ["full"] }
